export const EQUIPMENT = [
  "Ab Wheel",
  "Barbell",
  "Battle Ropes",
  "Bodyweight",
  "Cable",
  "Clubbell",
  "Dumbbell",
  "EZ Bar",
  "Gymnastic Rings",
  "Kettlebell",
  "Medicine Ball",
  "Miniband",
  "Parallette Bars",
  "Pull Up Bar",
  "Resistance Band",
  "Sliders",
  "Stability Ball",
  "Suspension Trainer",
  "Weight Plate",
] as const

export const EQUIPMENT_VI: Record<string, string> = {
  "Ab Wheel": "Bánh xe tập bụng",
  Barbell: "Thanh tạ đòn",
  "Battle Ropes": "Dây thừng chiến",
  Bodyweight: "Trọng lượng cơ thể",
  Cable: "Máy cáp",
  Clubbell: "Tạ chùy",
  Dumbbell: "Tạ đơn",
  "EZ Bar": "Thanh EZ",
  "Gymnastic Rings": "Vòng treo",
  Kettlebell: "Tạ ấm",
  "Medicine Ball": "Bóng thuốc",
  Miniband: "Dây kháng lực nhỏ",
  "Parallette Bars": "Xà parallette",
  "Pull Up Bar": "Xà đơn",
  "Resistance Band": "Dây kháng lực",
  Sliders: "Đĩa trượt",
  "Stability Ball": "Bóng ổn định",
  "Suspension Trainer": "Dây treo (TRX)",
  "Weight Plate": "Đĩa tạ",
}

export const POPULAR_EQUIPMENT: Set<string> = new Set([
  "Bodyweight",
  "Dumbbell",
  "Barbell",
  "Kettlebell",
  "Resistance Band",
])
