import { Exercise } from '@/types'

export const MOCK_EXERCISES: Exercise[] = [
  {
    id: '1',
    name: 'Barbell Back Squat',
    muscleGroup: 'Legs',
    level: 'Intermediate',
    equipment: 'Barbell',
    sets: 4,
    reps: '8-10',
    restSeconds: 90,
    description: 'Đứng thẳng, đặt tạ lên vai, hạ người xuống cho đến khi đùi song song với sàn. Giữ lưng thẳng và gối không vượt quá mũi chân.',
    trainer: 'Minh Trần',
  },
  {
    id: '2',
    name: 'Dumbbell Romanian Deadlift',
    muscleGroup: 'Legs',
    level: 'Intermediate',
    equipment: 'Dumbbell',
    sets: 3,
    reps: '10-12',
    restSeconds: 60,
    description: 'Cầm tạ đôi, hạ người về phía trước bằng cách đẩy hông ra sau, giữ lưng thẳng. Cảm nhận sự căng ở cơ sau đùi rồi đứng thẳng lại.',
    trainer: 'Linh Võ',
  },
  {
    id: '3',
    name: 'Seated Cable Row',
    muscleGroup: 'Back',
    level: 'Intermediate',
    equipment: 'Cable',
    sets: 5,
    reps: '10-12',
    restSeconds: 60,
    description: 'Ngồi trên ghế cáp, kéo tay cầm về phía bụng dưới, khuỷu tay gần sát cơ thể. Bóp cơ lưng và từ từ trả về vị trí ban đầu.',
    trainer: 'Hương Nguyễn',
  },
  {
    id: '4',
    name: 'Standing Barbell Shoulder Press',
    muscleGroup: 'Shoulders',
    level: 'Intermediate',
    equipment: 'Barbell',
    sets: 4,
    reps: '6-8',
    restSeconds: 90,
    description: 'Đứng thẳng, đặt tạ ngang vai, đẩy thẳng lên trên đầu. Không ưỡn lưng quá mức. Hạ tạ xuống từ từ và kiểm soát.',
    trainer: 'Nam Phạm',
  },
  {
    id: '5',
    name: 'Dumbbell Bench Press',
    muscleGroup: 'Chest',
    level: 'Intermediate',
    equipment: 'Dumbbell',
    sets: 4,
    reps: '8-10',
    restSeconds: 60,
    description: 'Nằm trên ghế phẳng, cầm tạ đôi ngang ngực, đẩy lên thẳng. Hạ tạ xuống từ từ để cơ ngực căng tối đa.',
    trainer: 'Huy Lê',
  },
  {
    id: '6',
    name: 'Bent-over Barbell Row',
    muscleGroup: 'Back',
    level: 'Intermediate',
    equipment: 'Barbell',
    sets: 4,
    reps: '6-8',
    restSeconds: 90,
    description: 'Cúi người về phía trước ~45°, kéo tạ thẳng lên phía bụng. Giữ lưng thẳng, khuỷu tay kéo về phía sau.',
    trainer: 'Minh Trần',
  },
  {
    id: '7',
    name: 'Walking Lunges',
    muscleGroup: 'Legs',
    level: 'Beginner',
    equipment: 'Bodyweight',
    sets: 3,
    reps: '12 each',
    restSeconds: 60,
    description: 'Bước dài về phía trước, hạ gối sau gần chạm sàn. Đẩy từ gót chân trước để bước tiếp. Giữ thân người thẳng đứng.',
  },
  {
    id: '8',
    name: 'Seated Dumbbell Press',
    muscleGroup: 'Shoulders',
    level: 'Beginner',
    equipment: 'Dumbbell',
    sets: 3,
    reps: '8-10',
    restSeconds: 60,
    description: 'Ngồi trên ghế có tựa lưng, cầm tạ ngang tai, đẩy thẳng lên. Hạ tạ từ từ xuống vị trí ban đầu.',
    trainer: 'Linh Võ',
  },
]

export const DEFAULT_EXERCISES = MOCK_EXERCISES.slice(0, 4)
